### PR TITLE
check bridge's port state

### LINKED ISSUE #463: GratuitousArp not work,  bridge can not receive arp package
when create pod,  GratuitousArp  can only receive by veth on host, bridge can not get arp package by tcpdump
https://github.com/containernetworking/plugins/blob/master/plugins/main/bridge/bridge.go#L472

if add sleep here, will work well
```
		// Send a gratuitous arp
		for _, ipc := range result.IPs {
			if ipc.Version == "4" {
				time.Sleep(1 * time.Second)
				_ = arping.GratuitousArpOverIface(ipc.Address.IP, *contVeth)
			}
		}
```

### PR DESCRIPTION
**Pull request by hongli-my**
fix #463
link host veth pair to bridge, the Initial state
of port is BR_STATE_DISABLED and change to
BR_STATE_FORWARDING async.

### CODE REVIEW

File: plugins/main/bridge/bridge.go [hunk 1]
```diff
@@ -465,8 +461,35 @@ func cmdAdd(args *skel.CmdArgs) error {
 			if err := ipam.ConfigureIface(args.IfName, result); err != nil {
 				return err
 			}
+			return nil
+		}); err != nil {
+			return err
+		}
+
+		// check bridge port state
```
Comment (squeed) [inline plugins/main/bridge/bridge.go:469]: "wait for bridge port state to be Up"

File: plugins/main/bridge/bridge.go [hunk 2]
```diff
@@ -465,8 +461,35 @@ func cmdAdd(args *skel.CmdArgs) error {
...
+		for i := 0; i < 3; i++ {
```
Comment (squeed) [inline plugins/main/bridge/bridge.go:470]: It would be nice if this had some backoff - sleeping 50, then, 500, then 1000 ms.

A more idiomatic way of writing this might be
```go
retries := []int{50, 500, 1000, 1000}
for idx, sleep := range retries {
  (check host)
  if idx == len(retries) - 1) {
    fail
  }
  time.Sleep(sleep + time.Millisecond)
}
```

Comment (hongli-my) [reply plugins/main/bridge/bridge.go]: @squeed    have been modified.

**Comment by squeed** [comment]
lgtm

File: plugins/main/bridge/bridge.go [hunk 3]
```diff
@@ -465,8 +461,36 @@ func cmdAdd(args *skel.CmdArgs) error {
...
+		for idx, sleep := range retries {
+			hostVeth, err := netlink.LinkByName(hostInterface.Name)
+			if err != nil {
+				return err
+			}
+			if hostVeth.Attrs().OperState == netlink.OperUp {
+				break
+			}
+
+			if idx == len(retries)-1 {
```
Comment (mars1024) [inline plugins/main/bridge/bridge.go:480]: If we try to escape from here, we only try 4 times and need 3 intervals, so I think we should sleep in the beginning of the loop and let `retries := []int{0,50,500,1000,1000}` , so we will make full use of `retries`.

File: plugins/main/bridge/bridge.go (hunk 1 above)
Comment (mars1024) [reply plugins/main/bridge/bridge.go:469]: nit: should we make this section into to a utility function?

File: plugins/main/bridge/bridge.go (hunk 3 above)
Comment (hongli-my) [reply plugins/main/bridge/bridge.go:480]: @mars1024   add it.

Comment (mars1024) [reply plugins/main/bridge/bridge.go:480]: Sorry, I think sleep should be the first step of the loop... just like
```golang
retries := []int{0, 50, 500, 1000, 1000}
for idx, sleep := range retries {
  time.Sleep(sleep * time.Millisecond)

  (check host)

  if idx == (len(retries) - 1) {
    fail
  }
}
```

Comment (hongli-my) [reply plugins/main/bridge/bridge.go:480]: sleep 0 before   do something ?

Comment (mars1024) [reply plugins/main/bridge/bridge.go:480]: yes, 0 means no sleep in the first time, then we will have 5 tries and 4 non-zero intervals as expectation.

Comment (hongli-my) [reply plugins/main/bridge/bridge.go:482]: @mars1024 ,  have changed.

**Comment by dcbw** [comment]
lgtm
