### PR TITLE
Fix vendor regression in dhcp4server

### LINKED ISSUE #206: dhcp4server vendor regression
plugins/vendor/github.com/d2g/dhcp4server lost a fix in leasepool/memorypool/memorypool.go that causes dhcp_test.go to fail.

### PR DESCRIPTION
**Pull request by mccv1r0**
vendor: update dhcp4server 

Bring plugins/vendor/github.com/d2g/dhcp4server up to date.

Fixes #206

### CODE REVIEW

**Comment by squeed** [comment]
Hmm, the test failures don't actually look like flakes - they're some kind of DHCP errors.

**Comment by mccv1r0** [comment]
The test fails because socketPath (/run/cni/dhcp.sock) isn't found.

```
• Failure in Spec Setup (BeforeEach) [15.021 seconds]
DHCP Operations [BeforeEach] configures and deconfigures a link with ADD/DEL 
/home/travis/gopath/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/plugins/ipam/dhcp/dhcp_test.go:214
  Timed out after 15.000s.
  Expected
      <bool>: false
  to be true
```
```
		// Wait up to 15 seconds for the client socket
		Eventually(func() bool {
			_, err := os.Stat(socketPath)
			return err == nil
		}, time.Second*15, time.Second/4).Should(BeTrue())
```
Locally, I've had it fail right in the middle of the test.  e..g cmdAdd found /run/cni/dhcp.sock and shortly after cmdDel couldn't find /run/cni/dhcp.sock.

Each run results in something different, all related to /run/cni/dhcp.sock not being there.

Commenting out os.Remove(socketPath)...

```
var _ = AfterSuite(func() {
	//os.Remove(socketPath)
	os.Remove(pidfilePath)
```

... and in AfterEach() results in test always passing

**Comment by dcbw** [comment]
The DHCP failures are pretty odd, we're tracking them down.  I can't get them to fail locally myself, but we'll figure it out.

**Comment by rosenhouse** [comment]
Hmm, is it really necessary to disable all test parallelization just to fix this problem?  Could we instead make `socketPath` be configurable at runtime (args or env var) so that each test could get a unique socket?

**Comment by dcbw** [comment]
> Hmm, is it really necessary to disable all test parallelization just to fix this problem? Could we instead make `socketPath` be configurable at runtime (args or env var) so that each test could get a unique socket?

@rosenhouse we thought about that too.  It would require pretty invasive changes since we'd need to plumb the socket path through both the server-side code (with a CLI flag) and the CNI JSON config as well.  All to make the testcase work; it wouldn't really be used in normal operation.  But yes, that is a potential fix.

What was really odd to Michael and I was that Ginkgo parallelized tests *in the same _test.go file*, as opposed to just files in the same directory or different packages.  Anyway, that's how it is I guess...

File: plugins/ipam/dhcp/dhcp_test.go [hunk 1]
```diff
@@ -99,6 +110,10 @@ const (
 	pidfilePath  string = "/var/run/cni/dhcp-client.pid"
 )
 
+var socketPath string
+var tmpDir string
+var err error
+
 var _ = BeforeSuite(func() {
 	os.Remove(socketPath)
 	os.Remove(pidfilePath)
```
Comment (dcbw) [inline plugins/ipam/dhcp/dhcp_test.go]: I don't think we need the Remove() for socketPath and pidfilePath anymore, since we're calling RemoveAll on the directory they are in.  Same for AfterSuite()

File: plugins/ipam/dhcp/dhcp_test.go [hunk 2]
```diff
@@ -107,6 +122,7 @@ var _ = BeforeSuite(func() {
 var _ = AfterSuite(func() {
 	os.Remove(socketPath)
 	os.Remove(pidfilePath)
+	defer os.RemoveAll(tmpDir)
```
Comment (dcbw) [inline plugins/ipam/dhcp/dhcp_test.go]: And actually, we don't even need this right?  We should put the RemoveAll(tmpDir) inside the AfterEach(), since it'll be unique to each testcase.  This RemoveAll() call in AfterSuite would only remove the last testcase tmpdir, which should already have been done by AfterEach()

File: plugins/ipam/dhcp/dhcp_test.go [hunk 3]
```diff
@@ -118,6 +134,10 @@ var _ = Describe("DHCP Operations", func() {
 	BeforeEach(func() {
 		dhcpServerStopCh = make(chan bool)
 
+		tmpDir, err = getTmpDir()
```
Comment (dcbw) [inline plugins/ipam/dhcp/dhcp_test.go]: We should balance this in AfterEach() with a os.RemoveAll(tmpDir) to clean things up for each test.

Comment (mccv1r0) [reply plugins/ipam/dhcp/dhcp_test.go]: I fixed this in last push which ensured that /run/cni existed.    (I was able to reproduce test "hang" when /run didn't contain cni directory)

File: plugins/ipam/dhcp/dhcp_test.go (hunk 1 above)
Comment (mccv1r0) [reply plugins/ipam/dhcp/dhcp_test.go]: pidfilePath is (currently) in /var/run/cni, not /run/cni.  Should it be moved to /run/cni?

File: plugins/ipam/dhcp/dhcp_test.go [hunk 4]
```diff
@@ -97,16 +108,16 @@ const (
 	hostVethName string = "dhcp0"
 	contVethName string = "eth0"
 	pidfilePath  string = "/var/run/cni/dhcp-client.pid"
```
Comment (dcbw) [inline plugins/ipam/dhcp/dhcp_test.go]: I don't think we need pidfilePath as a global constant anymore either.

Comment (mccv1r0) [reply plugins/ipam/dhcp/dhcp_test.go]: Agreed.  Removed.

File: plugins/ipam/dhcp/dhcp_test.go [hunk 5]
```diff
@@ -97,16 +108,16 @@ const (
...
+	cniDirPrefix string = "/var/run/cni"
 )
 
-var _ = BeforeSuite(func() {
-	os.Remove(socketPath)
-	os.Remove(pidfilePath)
-})
+var socketPath string
+var tmpDir string
+var err error
```
[the remark this answers is not in the document]
Comment (mccv1r0) [reply plugins/ipam/dhcp/dhcp_test.go]: Moved to the var() section of Describe().  Tested with both -p and without.

File: plugins/ipam/dhcp/main.go [hunk 6]
```diff
@@ -28,18 +29,24 @@ import (
 	"github.com/containernetworking/cni/pkg/version"
 )
 
-const socketPath = "/run/cni/dhcp.sock"
+const defaultSocketPath = "/run/cni/defaultdhcp.sock"
```
Comment (squeed) [inline plugins/ipam/dhcp/main.go]: We should keep the same default path.
