### PR TITLE
Increase IfbDeviceName size and refactor hashing functions, fix

### LINKED ISSUE #347: ifb device name hash collisions
Hi all! (long time, I'm back to this for at least a tiny bit)

We got this issue reported in Cloud Foundry: https://github.com/cloudfoundry/silk-release/issues/13

Summary: the bandwidth plugin [creates an IFB device with a name based on only 16 bits of hash material of the container id](https://github.com/containernetworking/plugins/blob/0eddc554c0747200b7b112ce5322dcfa525298cf/plugins/meta/bandwidth/main.go#L114-L122):
```go
func getIfbDeviceName(networkName string, containerId string) (string, error) {
	hash := sha1.New()
	_, err := hash.Write([]byte(networkName + containerId))
	if err != nil {
		return "", err
	}

	return fmt.Sprintf("%x", hash.Sum(nil))[:4], nil
}
```

When you do some basic [birthday problem](https://en.wikipedia.org/wiki/Birthday_problem) math, you discover that with a hundred containers on a single host, the chance of has collision (more than one IFB device with the same name) is close to 10%.

Since the interface name length can be up to 15 characters, we're thinking of mitigating this by changing the above `[:4]` to `[:12]` or `[:14]`.  That should reduce the chance of collision to below 1 in 10^7 even with 500 containers per host.

Anyone got other ideas for less-probabilistic fixes?

### PR DESCRIPTION
**Pull request by mike1808**
* Extract all hashing usage into `pkg/utils/hash` and refactored all usages
* Refactor duplication FormatChainName
* Fixes #347 

Co-authored-by: Cameron Moreau <cmoreau@pivotal.io>

cc @rosenhouse

### CODE REVIEW

File: pkg/utils/hash/hash.go [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+import (
+	"crypto/sha512"
+	"fmt"
+)
+
+const maxLen = sha512.Size * 2
+
+func New(input string, length int) (string, error) {
+	if length <= 0 || length > maxLen {
+		return "", fmt.Errorf("only length between 1 and 128 are supported")
```
Comment (jellonek) [inline pkg/utils/hash/hash.go]: Hmmm... IMO instead of 128 there should be used `maxLen` value, so if someday we would switch from sha512 to something other - this would be still correct.

File: pkg/utils/utils.go [hunk 2]
```diff
@@ -29,9 +30,13 @@ const (
 // Ensures that the generated chain name is exactly
 // maxChainLength chars in length
 func FormatChainName(name string, id string) string {
-	chainBytes := sha512.Sum512([]byte(name + id))
-	chain := fmt.Sprintf("%s%x", chainPrefix, chainBytes)
-	return chain[:maxChainLength]
+	return FormatChainNameWithPrefix(name, id, "")
```
Comment (jellonek) [inline pkg/utils/utils.go]: Could you update there docstring (and also add one to next func) according to https://github.com/golang/go/wiki/CodeReviewComments#doc-comments and https://golang.org/doc/effective_go.html#commentary
Especially I'm asking about:
```
If every doc comment begins with the name of the item it describes, you can use the doc subcommand of the go tool and run the output through grep. Imagine you couldn't remember the name "Compile" but were looking for the parsing function for regular expressions, so you ran the command,

$ go doc -all regexp | grep -i parse
```

File: pkg/utils/utils_test.go [hunk 3]
```diff
@@ -20,32 +20,70 @@ import (
 )
 
 var _ = Describe("Utils", func() {
-	It("must format a short name", func() {
-		chain := FormatChainName("test", "1234")
-		Expect(len(chain)).To(Equal(maxChainLength))
-		Expect(chain).To(Equal("CNI-2bbe0c48b91a7d1b8a6753a8"))
-	})
+	Context("FormatChainName", func() {
```
Comment (rosenhouse) [inline pkg/utils/utils_test.go]: Idiomatic Ginkgo would have this be a `Describe` instead of `Context`.  So that the full test can be read in English like
> Describe [the function] FormatChainName [, ] It must format a short name

File: pkg/utils/utils.go [hunk 4]
```diff
@@ -29,9 +30,13 @@ const (
...
+}
+
+func FormatChainNameWithPrefix(name string, id string, prefix string) string {
+	length := maxChainLength - prefixLength - len(prefix)
+	chain, _ := hash.New(name+id, length)
```
Comment (rosenhouse) [inline pkg/utils/utils.go]: Discarding this error seems risky.  The caller could pass in a long `prefix` string which could cause `length` to become less than 1.  Better to either
1. return the error up to the caller, or
2. alternately, have the `hash.New` internally `panic`.  But "[library functions should avoid panic](https://golang.org/doc/effective_go.html#panic)" and I'd only suggest doing that if we were confident that it was always a programmer error and not a user-input or environment issue.

File: plugins/meta/bandwidth/bandwidth_linux_test.go [hunk 5]
```diff
@@ -105,7 +105,7 @@ var _ = Describe("bandwidth test", func() {
 		hostIP = net.IP{169, 254, 0, 1}
 		containerIP = net.IP{10, 254, 0, 1}
 		hostIfaceMTU = 1024
-		ifbDeviceName = "5b6c"
+		ifbDeviceName = "a8eda89404b7c8"
```
[the remark this answers is not in the document]
Comment (cameronmoreau) [reply plugins/meta/bandwidth/bandwidth_linux_test.go]: That makes sense 👍 

Since "b" is a valid hex character, @mike1808 and I have decided on the prefix "bw" to avoid confusion

**Comment by mike1808** [comment]
Thanks for the review! Check new changes for the fixes @rosenhouse @jellonek

File: plugins/meta/bandwidth/main.go [hunk 6]
```diff
@@ -112,13 +114,11 @@ func validateRateAndBurst(rate int, burst int) error {
 }
 
 func getIfbDeviceName(networkName string, containerId string) (string, error) {
-	hash := sha1.New()
-	_, err := hash.Write([]byte(networkName + containerId))
+	hash, err := hash.New(networkName+containerId, maxIfbDeviceLength-3)
```
Comment (shawn-ogg) [inline plugins/meta/bandwidth/main.go]: Is `-3` correct? I see that you append "bw" to the return value which has only a length of `2`

**Comment by mike1808** [comment]
Hey @shawn-ogg , do you have a specific use-case where you would run multiple bandwidth plugins per container?  We'd like to do more research on this, but our assumption is that every `containerId` would be unique (not sure about `networkName`).

Correct me if I'm wrong but, I think the current (on master) implementation will result in all `sha1(networkName, containerId)` being unique, but the collision happens when those sha's share the same first 4 digits.

Also the [cmdDel() method](https://github.com/containernetworking/plugins/blob/966bbcb8a572aa4c253ea9650888ad2306e3c8f2/plugins/meta/bandwidth/main.go#L242) relies on `getIfbDeviceName()` to be deterministic (given the same name and containerId).

cc @cameronmoreau

File: plugins/meta/bandwidth/main.go (hunk 6 above)
Comment (rosenhouse) [reply plugins/meta/bandwidth/main.go]: Yeah, it'd much rather have 
```golang
const ifbDeviceNamePrefix = "bw"
```
and
```golang
hash.New(..., maxIfbDeviceLength-len(ifbDeviceNamePrefix))
```

File: pkg/utils/utils.go (hunk 4 above)
Comment (rosenhouse) [reply pkg/utils/utils.go]: You're still discarding this error, no?

**Comment by cameronmoreau** [comment]
> In general I think you just made the possibility of an name collision smaller (by a lot). But the main issue still remains: the hash is calculated from the `networkName` and `containerId`. If there is a name collision we stuck, because a rerun would still end up with the same hash.
> One solution could be to add some randomness (e.g. the timestamp) to it. Of course only if there is no other place where you must deduce the ifname using the hash function (I'm not aware of it).
> 
> Another approach would be to use random strings:
> (e.g. https://github.com/dchest/uniuri)
> and implement a retry in the unlikely event of a clash.

@shawn-ogg I think you may have found a bug (or new features?) in the existing bandwidth plugin 🎉I don't believe you can run multiple bandwidth plugins in a single container today, as the `networkName` and `containerId` will not be different. What are your thoughts on opening a separate issue for this?

cc @mike1808 @rosenhouse

**Comment by squeed** [comment]
lgtm!
