### PR TITLE
host-local: remove redundant startRange in RangeIterator to avoid mismatching with startIP

### LINKED ISSUE #596: CI failing on "could not add VRF vrf0: operation not supported"
As @mars1024 notes,
> I think the CI has been breaking for a while since [this commit](https://github.com/containernetworking/plugins/commit/0ea07b826990e4475bbe06110f456ac0a648e6ee)

Logs: https://github.com/containernetworking/plugins/runs/2023007076
```
Running Suite: plugins/meta/vrf
===============================
Random Seed: 1614783395
Will run 18 of 18 specs

• Failure [0.007 seconds]
vrf plugin
/home/runner/work/plugins/plugins/plugins/meta/vrf/vrf_test.go:77
  passes prevResult through unchanged [It]
  /home/runner/work/plugins/plugins/plugins/meta/vrf/vrf_test.go:125

  Unexpected error:
      <*errors.errorString | 0xc0000a6a10>: {
          s: "cmdAdd failed: could not add VRF vrf0: operation not supported",
      }
      cmdAdd failed: could not add VRF vrf0: operation not supported
  occurred

  /home/runner/work/plugins/plugins/plugins/meta/vrf/vrf_test.go:141
```

### PR DESCRIPTION
**Pull request by mars1024**
Ref to #579 , just try another way to fix the same issue. Here is the details [https://github.com/containernetworking/plugins/pull/579#issuecomment-772466664](https://github.com/containernetworking/plugins/pull/579#issuecomment-772466664).

Signed-off-by: Bruce Ma <brucema19901024@gmail.com>

Fixes #596

### CODE REVIEW

File: plugins/ipam/host-local/backend/allocator/allocator.go [hunk 1]
```diff
@@ -215,6 +215,7 @@ func (i *RangeIter) Next() (*net.IPNet, net.IP) {
 
 	if i.startIP == nil {
 		i.startIP = i.cur
+		i.startRange = i.rangeIdx
 	} else if i.rangeIdx == i.startRange && i.cur.Equal(i.startIP) {
```
Comment (squeed) [inline plugins/ipam/host-local/backend/allocator/allocator.go:219]: Now that I look at this, do we even need `startRange`? Since we validate that ranges can't overlap, that should be sufficient, right?

Comment (mars1024) [reply plugins/ipam/host-local/backend/allocator/allocator.go:219]: haha, good self-question :) , maybe I should walk all lines to figure this out

Comment (dcbw) [reply plugins/ipam/host-local/backend/allocator/allocator.go:219]: @mars1024 any thoughts on whether we can remove `startRange`?

Comment (mars1024) [reply plugins/ipam/host-local/backend/allocator/allocator.go]: yeah, I think `startRange` is redundant and I'll remove it

**Comment by mars1024** [comment]
Through the advice from @squeed , I've removed the redundant `startRange` to resolve this mismatching issue, which seems more brief and clean. 
/cc @dcbw @bboreham

**Review by bboreham — APPROVED** [review]
lgtm, thanks!

**Comment by squeed** [comment]
This looks awesome, thanks!
